---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: volume-exporter
spec:
  rules:
  - http:
      paths:
      - path: /argo
        backend:
          serviceName: argocd-server
          servicePort: http